### PR TITLE
Lru cache

### PR DESCRIPTION
**Pull request by tommyvn**
Add an lru cache for container detail requests to docker. It uses container ID and the container status as cache keys with the assumption that if these two things remain the same the rest of the container details will also be the same, a safe assumption to make for any container created by captain.
The cache size is hard-coded at 1024 due to the Config object being passed into the Connection object only at instantiation time. This mechanism should be reworked one day to make config of lru size and other variables more flexible.

### CODE REVIEW

**Comment by eddgrant** [comment]
Any tests around this new behaviour?

**Comment by tommyvn** [comment]
It's a stdlib module, so probably loads.

**Comment by tommyvn** [comment]
well, backports, but backport of a stdlib

**Comment by eddgrant** [comment]
Sorry, I probably wasnt clear in my earlier comment, I actually meant around our implementation around the cache. For example have we defined any acceptance criteria around what we expect to pull out of the cache in terms of the keys we use (you mentioned container id and container status) and the values we map to those keys?

**Comment by tommyvn** [comment]
If using this external module broke anything with regards to captain the captain unit tests would fail because you'd not get expected output from a given input. lru_cache is simply an internal implementation detail of a specific unit which is indeed already tested as a whole, in this case the get_node_instances function, right? Every unit test that has more than one test container uses the cache, and every unit test that removes a container asserts that the cache picks up the new container state and so behaves correctly. Maybe you're thinking of a specific issue tho?

**Comment by eddgrant** [comment]
Regarding specific issues I was just looking at the new lines of code and was trying to figure out how they would be used, which was difficult as I couldn't figure out how the existing tests exercised them. 

For example, regarding the following new lines:

    # Grab the first part of State to give uniqueness of container and state for the lru_cache
    full_container_status = container["Status"]
    container_status = full_container_status.split()[0] if full_container_status else full_container_status

In trying to figure out _why_ the ``if`` and the ``else`` statements returned the same value I felt it might have been easier to determine (and thus review the change) had a test existed to demonstrate the intention of that code. Off the top of my head I couldn't identify a situation where we'd enter the ``else`` case other than if ``full_container_status`` was either None or a boolean of ``False``, the former case would run through but would return a value of ``None`` however the latter case would fail with the error: ``AttributeError: 'bool' object has no attribute 'split'``. I'm probably missing something really obvious though, perhaps you could walk me through it tomorrow.

**Comment by tommyvn** [comment]
Makes sense, I've flipped the dead container conditional to make Up the only running status and added another test container to better explain the split.
It's not different types it's there to catch but rather empty statuses, if you'd like to see the failure you can remove the fallback and it should fail on that new test container.

**Comment by eddgrant** [comment]
Thanks for adding the tests, I see what you're doing now. One final comment (sorry!) - I think the ordering of the items in the list, as returned by ``connection.get_instances()`` is non-deterministic. This is fine however the ``test_returns_all_instances_with_ports`` test expects them to be deterministic and so fails intermittently (I get about 1 in 10 failures). Probably worth changing the test to look expect the instances to appear in any of the positions of the list.

**Comment by eddgrant** [comment]
Sorry - closed by accident! Reopening.

**Comment by tommyvn** [comment]
good catch, I've sorted the return from `connection.get_instances()` to make the ordering deterministic in the tests.

**Pull request merged**
